version: '3'
services:
  database:
    image: docker.io/library/postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foobar1234
      POSTGRES_DB: booklist-db
  backend:
    build: .
    container_name: booklist
    ports:
      - "8080:8080"
    volumes:
      - ./local-config.yaml:/config/database.yaml